development:
#  dialect: sqlite3
  dialect: mysql
#  datasource: test.db
#  datasource: user_name:password@tcp(127.0.0.1)/dbname?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  datasource: root:@/laravel6?charset=utf8&parseTime=True&loc=Local
#  dir: migrations/sqlite3
  dir: db/migrations

#production:
#  dialect: postgres
#  datasource: dbname=myapp sslmode=disable
#  dir: migrations/postgres
#  table: migrations